version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:17.4-alpine3.21
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pearlcard_db
    ports:
      - "5432:5432"


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pearlcard-backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py makemigrations && python manage.py migrate && python manage.py loaddata zones.json && python manage.py runserver 0.0.0.0:8000
        "
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pearlcard_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  react-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pearlcity-frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data: